Add ability to store and elipsize dynamic menu item lengths
AyatanaIndicators/libayatana-common pull request #25
Opened 2021-06-14 21:23 UTC by tari01

This is a base for fixing issues such as https://github.com/AyatanaIndicators/ayatana-indicator-datetime/issues/29 and https://github.com/AyatanaIndicators/ayatana-indicator-notifications/issues/18.

2021-06-15 05:44 UTC, sunweaver requested changes
Cool. Thanks for implementing this so meticulously and even making the string length that defines when to elipsize configurable. However, I have some feedback that requires a second iteration of development. Mainly dropping your own GSettings module and re-using what we already have in cmake-extras.

2021-06-15 05:44 UTC, sunweaver commented on src/utils.h
> +void ayatana_common_utils_elipsize(char *sText);
Urgh, don't split prototype definition and code for it into two different commits. Please unite them.

2021-06-15 05:44 UTC, sunweaver commented on src/utils.c
> +void ayatana_common_utils_elipsize(char *sText)
Please unite with prototype addition.

2021-06-15 05:44 UTC, sunweaver commented on cmake/UseGSettings.cmake
> +macro(add_schema SCHEMA_NAME)
Please don't ship yet another GSettings CMake module with this PR. Please use the GSettings module from cmake-extras. Thanks.

2021-06-15 15:32 UTC, tari01 commented
> Cool. Thanks for implementing this so meticulously and even making the string length that defines when to elipsize configurable. However, I have some feedback that requires a second iteration of development. Mainly dropping your own GSettings module and re-using what we already have in cmake-extras.

@sunweaver Done.

2021-06-15 17:53 UTC, sunweaver requested changes
Hmmm... well. Sorry for being so picky, but we need to improve some Git usage standards. Technically this complete PR is ok. Documentation-wise (Git commits, messages, what is committed together, etc.) this PR needs to be reworked.

Please make sure that after two years we understand what and why we did this change. The only tool we have for this is the documentation system provided by Git, i.e. the commit messages.

2021-06-15 17:53 UTC, sunweaver commented on data/CMakeLists.txt
> +add_schema("org.ayatana.common.gschema.xml")
This commit leaves the project in a broken state. Please commit `org.ayatana.common.gschema.xml` with it.

2021-06-15 17:53 UTC, sunweaver commented on tests/CMakeLists.txt
> +    ${GLIB_LIBRARIES}
Why commit this and the test file where it is required separately?

2021-06-15 17:53 UTC, sunweaver commented on tests/CMakeLists.txt
> +    ${GLIB_LIBRARIES}
We loose context with these atomics commits.

Normally, I'd expect: code change, unit tests and build system adaptations in one commit. With some proper commit message that describes what this change does.

2021-06-15 17:53 UTC, sunweaver commented on tests/tst_utils.cpp
> +class StringFunctionsTest : public ::testing::Test
Please commit this together with the function the test is for.

2021-06-15 17:53 UTC, sunweaver commented on CMakeLists.txt
> +add_subdirectory(data)
This should go with the commit that adds the CMakeLists.txt file and the .xml file.

2021-06-15 17:53 UTC, sunweaver commented on CMakeLists.txt
> +add_subdirectory(po)
This change should go with the commit that adds the po/ directory.

2021-06-15 20:37 UTC, tari01 commented
> Hmmm... well. Sorry for being so picky, but we need to improve some Git usage standards. Technically this complete PR is ok. Documentation-wise (Git commits, messages, what is committed together, etc.) this PR needs to be reworked.
> 
> Please make sure that after two years we understand what and why we did this change. The only tool we have for this is the documentation system provided by Git, i.e. the commit messages.

@sunweaver Please re-review.

2021-06-16 06:18 UTC, sunweaver approved these changes
LGTM now, thanks!

2021-06-16 06:30 UTC, merged

2021-06-16 06:31 UTC, sunweaver commented
@tari01: I have reworked the commit messages once more and merged two of the three commits into one. But it is merged now.