Add ayatana-indicators.target and systemd dependency
AyatanaIndicators/libayatana-common pull request #26
Opened 2021-06-15 00:03 UTC by tari01

2021-06-15 05:49 UTC, sunweaver requested changes
There is one open question on this.

Furthermore, your commits are two atomic these days for my personal taste. Please reduce this PR to three commits: upstream changes, CI changes, debian/* changes (in that order).

Thanks btw. for adapting debian/*. Much appreciated.

2021-06-15 05:49 UTC, sunweaver commented on debian/rules
> +	rm -f debian/tmp/usr/lib/systemd/user/ayatana-indicators-pre.target
Why do we need this one?

2021-06-15 17:55 UTC, sunweaver commented
@tari01: Before I reject your second iteration here, as well. Please incorporate the information I provided via #25 and libayatana-indicator#51 in this PR reworking. Thanks.

2021-06-16 06:45 UTC, sunweaver commented
@tari01: Please rebase and amend this PR, so we can soon provide ayatana-indicator-common in libayatana-common. Thanks.

2021-06-16 09:11 UTC, tari01 commented
> @tari01: Please rebase and amend this PR, so we can soon provide ayatana-indicator-common in libayatana-common. Thanks.

@sunweaver Review time.

2021-06-16 12:53 UTC, sunweaver approved these changes
LGTM now! Thanks!

2021-06-16 13:27 UTC, merged